rails/client/app/bundles/Kaiju/components/Component/components/SafeRender/SafeRender.jsx
rails/client/app/bundles/Kaiju/components/Component/containers/ElementContainer.jsx
rails/client/app/bundles/Kaiju/components/Preview/Preview.jsx

Previously each individual React element within the preview would be wrapped in a SafeRender component to conditionally render an error if one occurred. 
This caused errors for components that needed to read props directly off of children because they would read the SafeRender props instead of the actual child's props. 
For the preview the entire workspace is wrapped in a single SafeRender that will display the error that occurred.

Fix: SafeRender the entire workspace

---

rails/client/app/bundles/Kaiju/components/Component/utilities/drag.js
rails/client/app/bundles/Kaiju/components/Project/components/Layers/Layers.jsx
rails/client/app/bundles/Kaiju/components/Project/utilities/drag.js

Disable the ability to drag the entire workspace. This prevents nesting workspaces.
@cerner/kaiju

Fix - Disable the ability to drag the entire workspace

---

.travis.yml
README.md
docker-compose.yml
node/Dockerfile
rails/Dockerfile

Changes
- Travis CI will automatically build docker images and push them to docker hub on non pull request master branch builds.
- Docker compose file now specifies traefik and redis images as well as specifying images for kaiju-node and kaiju-rails.
- ReadME has been updated to recommend a docker-compose pull before docker-compose build to pull the latest node and rails docker images instead of building them from scratch.
- node docker file now installs silently.
- rails docker file now removes an unneeded hack.
@cerner/kaiju

Travis CI will build and push latest docker images to dockerhub

---

Dockerfile
docker-compose.yml
node/appConfig.js
node/config/default.js
node/config/development.js
node/config/production.js
node/config/test.js
node/service/controllers/code.js
node/service/controllers/preview.js
node/service/middlewares/Authentication.js
node/service/middlewares/FullUrl.js
node/service/utils/ServiceRequester.js
node/service_tests/jest/middlewares/Authentication.test.js
node/service_tests/jest/middlewares/FullUrl.test.js
node/service_tests/jest/utils/ServiceRequester.test.js
traefik.toml

When the root url is unknown use the request url, the proxy handles the request in all cases except when the root url is localhost in docker compose, in that case an override is required to appropriately re-direct the call.
I also added an express middleware to get the full url from the request.
@cerner/kaiju

Enable node server for cases when the root url is unknown

---

docker-compose.yml
traefik.toml

Remove rule to redirect to the rails server for the code route, until code build by the node server is presentable.
@cerner/kaiju

Clean up traefik rules.

---

rails/client/app/bundles/Kaiju/components/Component/utilities/dispatcher.js
rails/client/app/bundles/Kaiju/components/Project/components/ActionBar/ActionBar.jsx
rails/client/app/bundles/Kaiju/components/Project/utilities/messenger.js

Added keyboard shortcuts for copy and paste.
This enhancement uses the local browser storage for each browser.
- Cannot copy paste between different types of browsers. ( Copy in Safari -> Paste in Chrome )
- A component may only be pasted into a Placeholder
- A Workspace cannot be copied and pasted as a nested child in another Workspace, however, an entire Workspace can be replaced by the clipboard by pasting into the root placeholder of the Workspace. ( Click the placeholder in a new workspace and paste into it )
- Clickable copy and paste action buttons
- Add the clipboard as the first item in the editors Component Selection drop down to enable pasting into components that do not have a drop zone placeholder
There were several scenarios that I tested but there may be more.
- Copying an …

Update - Added copy and paste keyboard shortcuts

---

changelog.md
rails/app/controllers/components_controller.rb

Users were unable to access attributes on workspaces they were not collaborators on.
@cerner/kaiju

Fix - Enabled all logged in users to view component attributes

---

node/appConfig.js
node/package-lock.json
node/service/code_generation/CodeGenerator.js
node/service/kaiju_plugins/DefaultTerraPlugin.js
node/service/kaiju_plugins/PluginUtils.js
node/service/preview_generation/PreviewGenerator.js

This change will set us up to allow plugins to decide if they want/need webpack to create their preview.
Converted plugin from callbacks to promises.
Fallback file system is applied in the plugin.
Broke out common kaiju plugin utils.
@cerner/kaiju

Migrate node preview webpack from kaiju to plugin.

---

changelog.md
rails/client/app/bundles/kaiju/components/Project/components/Form/ComponentSelect/ComponentSelect.jsx

The Component drop down search within the editor was previously case sensitive. This fix makes the search case insensitive by providing a custom filter function. 
@cerner/kaiju

Fixed - Component drop down search case sensitivity

---

rails/app/controllers/projects_controller.rb

There is a bug where when you view a workspace owned by someone else you are not authorized to view the reference components for the project. This PR removes that requirement.
@cerner/kaiju

Do not require authorization to view project reference components

---

changelog.md
node/package-lock.json
node/package.json
rails/client/app/bundles/kaiju/components/Component/components/Element/Element.jsx
rails/client/app/bundles/kaiju/components/Component/containers/ComponentContainer.jsx
rails/client/app/bundles/kaiju/components/Component/reducers/reducers.js
rails/client/app/bundles/kaiju/components/Component/reducers/refreshedComponent.js
rails/client/package-lock.json
rails/client/package.json

- Pulling in Tabs
- Removed empty arrays from being passed as component props
- Conditionally force a re-render of the most recently refreshed component. This enables editing uncontrolled components and being able to see the changes without refreshing the screen.
- Enabled click propagation to allow click events to trigger default component functionality. ( Such as selecting tabs )
Blocked until the code merge and release of [terra-kaiju-plugin](https://github.com/cerner/terra-kaiju-plugin/pull/5)
@cerner/kaiju

Removed empty arrays and conditionally refresh components

---

changelog.md
docs/guide.md
rails/client/app/bundles/kaiju/components/Component/utilities/dispatcher.js
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx

Added a keyboard shortcut for duplicating a selected component.
Also updated the changelog to provide a link to the newly added guide.
This guide link will not work on github, but will work from the application.
Resolves: #https://github.com/cerner/kaiju/issues/78
@cerner/kaiju

Added - A keyboard shortcut for duplicating selected components

---

rails/client/app/bundles/kaiju/components/Component/utilities/dispatcher.js
rails/client/app/bundles/kaiju/utilities/axios.js

This pull requests adds the foundation for generic error handling.
The axios interceptors will intercept every request and evaluate the server response / error. If the server responds with an unauthorized status or doesn't respond at all the browser will reload the current page which will force a login.
There is some consideration and discussions for future changes needed for other errors that may need to provide a user with some visual feedback. JS error, internal error, etc...
Ideally 403 errors would be prevented by safeguards in the UI. This pull request will refresh the page on forbidden requests, this should probably be handled in another way in the future. Either by preventing the action entirely in the UI or notifying the user they are not authorized to take that action. 
Thanks …

Added - Scaffolding for unauthorized error handling

---

rails/client/package-lock.json
rails/client/package.json

This pull request upgrades the Kaiju client to Webpack 3 and updates a few of the resource loaders.
Resolves #82
> Migrating from webpack 2 to 3, should involve no effort beyond running the upgrade commands in your terminal. We marked this as a Major change because of internal breaking changes that could affect some plugins.
@cerner/kaiju

Updated - Upgrade to Webpack 3

---

rails/app/controllers/projects_controller.rb

When the change log is viewed the put to the server returns a 403 if the user is not a collaborator on the project.
The change log is never marked as viewed. 
Fixes #85
This pull request disables the collaborators check when the change log is viewed on a read-only project.
@cerner/kaiju

Updated - Disabled collaborators check to mark the change log as read

---

changelog.md
rails/client/app/bundles/kaiju/components/Project/components/Sandbox/Sandbox.jsx
rails/client/app/bundles/kaiju/components/Project/components/Sandbox/Sandbox.scss

Workspaces were unable to be resized larger than the available screen size. This fix enables an overflow so workspaces can be resized to all breakpoints regardless of screen size.
Fixes https://github.com/cerner/kaiju/issues/90
@cerner/kaiju

Fixed - Workspace resizing

---

node/package-lock.json
node/package.json
rails/changelog.md
rails/client/app/bundles/kaiju/components/Component/components/Element/Element.jsx
rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.jsx
rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.scss
rails/client/app/bundles/kaiju/components/Project/components/Editor/Editor.scss
rails/client/app/bundles/kaiju/components/Project/components/Form/ComponentSelect/ComponentSelect.jsx
rails/client/app/bundles/kaiju/components/Project/components/Form/ComponentSelect/ComponentSelect.scss
rails/client/package-lock.json
rails/client/package.json

- Added a preview for each Icon component in the Component Search and within the editor Component Search.
- Uplifted DraggableItem and ComponentSearch to use CSS Modules
An example of the IconMap can be found here: https://github.com/cerner/terra-kaiju-plugin/pull/12
Resolves #8.
@cerner/kaiju

Added - Icon previews

---

rails/app/views/layouts/application.html.erb
rails/app/views/layouts/code.html.erb
rails/app/views/layouts/components.html.erb
rails/app/views/layouts/guide.html.erb
rails/app/views/layouts/health.html.erb
rails/app/views/layouts/launch.html.erb
rails/app/views/layouts/preview.html.erb
rails/client/package-lock.json
rails/client/package.json
rails/client/webpack.config.js

Extracting the style sheets and loading them in parallel increases initial page load performance.
https://github.com/webpack-contrib/extract-text-webpack-plugin
Resolves #98.
@cerner/kaiju

Added - ExtractTextPlugin to load stylesheets in parallel to javascript assets

---

rails/changelog.md
rails/client/app/bundles/kaiju/components/Project/Project.scss
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Share/Share.jsx
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Share/Share.scss
rails/client/app/bundles/kaiju/components/Project/containers/menu/ShareMenuItem.jsx
rails/client/app/bundles/kaiju/components/Project/containers/menu/ShareMenuItem.scss

Reworked the UI of the share menu and added a Read-Only share option.
Previous UI:
Updated UI:
Resolves #106 
@cerner/kaiju

Added - A Read-Only link within the share menu

---

rails/client/app/bundles/kaiju/components/Project/containers/BrowserContainer.jsx

Users were running into issues with the default browser navigation actions. ( Back and Forward ). 
Kaiju updates the browser URL as workspaces are opened and closed so that the web url will always match the current workspace or project. This is done by pushing urls onto the browser history stack.
This resulted in creating really long navigation stacks as the user opened and closed tabs.
```
/workspace/1
/workspace/2
/workspace/4
/workspace/1
```
To fix this issue the URL will no longer be pushed onto the history stack, but rather replace the current stack index. This makes the single page navigation more intuitive. The stack no longer grows, clicking back will always take a user to the previous web url before they opened a Kaiju workspace or project regardless of how many workspaces they …

Fix - Browser navigation stack

---

rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx
rails/client/app/bundles/kaiju/components/Project/components/Sandbox/Sandbox.jsx
rails/client/app/bundles/kaiju/components/Project/containers/ActionBarContainer.jsx
rails/client/app/bundles/kaiju/components/Project/containers/SandboxContainer.jsx
rails/client/webpack.config.js

Updated - Removed editable actions from the ActionBar when viewing is read-only

---

rails/client/app/bundles/kaiju/components/Project/components/Tabs/Tab/Tab.jsx
rails/client/app/bundles/kaiju/components/Project/components/Tabs/Tab/Tab.scss
rails/client/app/bundles/kaiju/components/Project/containers/TabContainer.jsx
rails/client/app/bundles/kaiju/components/common/Card/Card.jsx

This change adds a title to Cards and Tabs to display the full text when hovered. This change also updates the Tab to use css modules.
Resolves #117 
This is a browser native title. The title will display after hovering the items for ~2 seconds.
@cerner/kaiju

Added - Native hover titles to Cards and Tabs

---

rails/client/.babelrc
rails/client/app/bundles/kaiju/components/Project/Project.jsx
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Delete/Delete.jsx
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Duplicate/Duplicate.jsx
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Rename/Rename.jsx
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Share/Share.jsx
rails/client/app/bundles/kaiju/components/Project/components/Form/Item/Item.scss
rails/client/app/bundles/kaiju/components/Project/components/Menu/Menu.scss
rails/client/app/bundles/kaiju/components/Project/components/Menu/MenuItem/MenuItem.scss
rails/client/app/bundles/kaiju/components/Project/components/Menu/SubMenu/SubMenu.scss
rails/client/app/bundles/kaiju/components/Project/components/Tabs/Tabs.scss
rails/client/app/bundles/kaiju/components/Project/containers/ProjectNameContainer.jsx
rails/client/app/bundles/kaiju/components/Project/containers/TabContainer.jsx
rails/client/app/bundles/kaiju/components/Project/containers/menu/DeleteMenuItem.jsx
rails/client/app/bundles/kaiju/components/Project/containers/menu/OpenMenuItem.jsx
rails/client/app/bundles/kaiju/components/Project/containers/menu/RenameMenuItem.jsx
rails/client/app/bundles/kaiju/components/common/SelectableList/SelectableList.scss
rails/client/app/bundles/kaiju/components/common/TreeView/TreeView.scss
rails/client/package-lock.json
rails/client/package.json
rails/client/themes/default.json
rails/client/webpack.config.js

Ant 3.0 Change Log: https://ant.design/changelog#3.0.0
Changes:
- Modals cannot be within the same click target that launches them. Many components previously using modals now return Arrays ( thanks to React 16 ) so the modal and click target are siblings.
- Ant removed the majority of the global styles, list specifically needed margin and padding style resets.
- Ant increased the default font-size, to remain visually passive we are utilizing ant's theming approach to revert it back. https://ant.design/docs/react/customize-theme
- Input refs changed slightly. 
Resolves #122.
@cerner/kaiju

Updated - Uplifted Ant Design to 3.0

---

rails/client/package-lock.json
rails/client/package.json
rails/client/webpack.config.js

Updated the entry packages to include the babel-polyfill. This will enable backwards compatibility of the workspace preview in older browsers, specifically IE 10.
@cerner/kaiju

Added the babel-polyfill to each entry

---

rails/client/package-lock.json
rails/client/package.json
rails/client/webpack.config.js

Upgraded to Webpack 4
- Replaced extract-text-webpack-plugin with mini-css-extract-plugin. extract-text-webpack-plugin is not compatible with Webpack 4 and recommended this change.
- Minified css and js assets in production 
Resolves #133.
@cerner/kaiju

Updated - Webpack to version 4

---

rails/config/application.rb

The logs from StackProf periodically fill up the available disk space and cause the deployment to crash. Disabling the logging until a better solution is found.
@cerner/kaiju

Update - Disabled StackProf logging to prevent maxing out disk space

---

rails/app/models/kaiju/user_json.rb
rails/changelog.md
rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.jsx
rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.scss
rails/client/app/bundles/kaiju/components/Project/containers/StoryBoardContainer.jsx
rails/lib/component_information.rb
rails/spec/models/kaiju/user_json_spec.rb

- Sorted the projects returned from the User JSON
- Sorted the workspace names within a project alphabetically
- Added the component version into the additional information tooltip
@cerner/kaiju

Updated - Sort project names alphabetically on the launch page

---

rails/app/controllers/workspaces_controller.rb
rails/app/views/layouts/preview.html.erb
rails/changelog.md
rails/spec/models/kaiju/user_json_spec.rb
traefik.toml

Updated the browser title to display the workspace name while in preview.
Previously the tab only displayed as "Kaiju"
@cerner/kaiju

Updated - The browser tab will now display the workspace name in preview

---

rails/changelog.md
rails/client/app/bundles/kaiju/components/Attributes/Attributes.jsx

The integer check for array indexes was returning false positives. This update parses the key before checking for number.
*Before*
*After*
@cerner/kaiju

Fixed - Attribute array generation

---

rails/changelog.md
rails/client/app/bundles/kaiju/components/Component/utilities/dispatcher.js
rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx

Returning false in functions bound using mousetrap will prevent default browser actions. 
https://github.com/ccampbell/mousetrap
Using the keyboard delete key to delete selected components was navigating the browser backwards in Firefox
@cerner/kaiju

Fixed - Prevent browser default actions for keyboard shortcuts

---

rails/app/views/layouts/application.html.erb
rails/app/views/layouts/attributes.html.erb
rails/app/views/layouts/code.html.erb
rails/app/views/layouts/components.html.erb
rails/app/views/layouts/guide.html.erb
rails/app/views/layouts/health.html.erb
rails/app/views/layouts/launch.html.erb
rails/app/views/layouts/preview.html.erb
rails/changelog.md

The views in Kaiju would scale content between devices, this fix sets an initial scale to preserve scaling between mobile, tablet and desktop.
Example of scaling: 
After Change:
@cerner/kaiju

Fixed - Corrected view scaling

---

client/package-lock.json
client/package.json

This PR updates the client package dependencies to pull in the latest released component changes.
This PR locks eslint to 6.5.0 due to eslint node support. The Kaiju image currently builds on node 8.9.2, however eslint's support requires >= 8.10.0
https://github.com/eslint/eslint/issues/12493

Update package dependencies
