cerner/kaiju

- rails/client/app/bundles/Kaiju/components/Code/Code.jsx
- rails/client/app/bundles/Kaiju/components/Component/components/Placeholder/Placeholder.jsx
- rails/client/app/bundles/Kaiju/components/Component/utilities/dispatcher.js
- rails/client/app/bundles/Kaiju/components/Component/utilities/highlight.js
- rails/client/app/bundles/Kaiju/components/Project/components/ActionBar/ActionBar.jsx
- rails/client/app/bundles/Kaiju/components/Project/components/ActionBar/Share/Share.scss
- rails/client/app/bundles/Kaiju/components/Project/components/Layers/Layers.jsx
- rails/client/app/bundles/Kaiju/components/Project/reducers/workspaces.js
- rails/client/app/bundles/Kaiju/components/common/SearchBar/SearchBar.scss
- rails/client/webpack.config.js
Here is a list of the errors that were fixed:
- Expected 'this' to be used by class method 'handleDrop'  class-methods-use-this
- 'error' is defined but never used  no-unused-vars
- 'getTargetLabel' is assigned a value but never used  no-unused-vars
- Expected 'this' to be used by class method 'deselect'  class-methods-use-this
- Expected 'this' to be used by class method 'destroy'   class-methods-use-this
- Expected 'this' to be used by class method 'scrollToComponent'  class-methods-use-this
- Unexpected lexical declaration in case block  no-case-declarations
- 'devBuild', 'webpackOutputPath', 'webpackPublicOutputDir' is assigned a value but never used                no-unused-vars
> Fix: All eslint errors

- .travis.yml
- package.json
This pr runs brakeman as part of CI
@cerner/kaiju
> Added: brakeman scanning to rails server

- app.json
- node/package.json
- package.json
It looks like I'll need to commit this to master to test the PR deployment. Thanks Heroku
@cerner/kaiju
> Added: an app.json to the repo

- .dockerignore
- node/.dockerignore
- node/package.json
- package.json
- rails/.dockerignore
- rails/Gemfile
- rails/Gemfile.lock
- rails/package.json
Added: Docker ignore files at root, node and rails folders
Removed: SqlLite dependency (unneeded)
Added: node version to package jsons
@cerner/kaiju
> Minor Cleanup

- Dockerfile
- package.json
- rails/Dockerfile
Dry up docker files by reusing base images
@cerner/kaiju
> Dry up dockerfiles

- node/appConfig.js
- node/service/controllers/code.js
- node/service/controllers/projectTypes.js
Minor clean up for json rendering
@cerner/kaiju
> clean up json rendering

- changelog.md
- node/package-lock.json
- rails/client/package-lock.json
After fixing my public profile the kaiju-bundle history was rewritten. This will sync the repository and should be the last time it is necessary. 
@cerner/kaiju
> Update - Bumping package lock to sync bundles

- rails/client/package-lock.json
- rails/client/package.json
Bumping marked to version 0.3.9
@cerner/kaiju
> Updated - Bumped marked to version 0.3.9

- rails/app/helpers/projects_helper.rb
- rails/app/helpers/workspaces_helper.rb
- rails/app/models/kaiju/component.rb
- rails/app/models/kaiju/component_factory.rb
- rails/app/models/kaiju/property.rb
- rails/app/models/kaiju/workspace.rb
- rails/app/models/kaiju/workspace_factory.rb
- rails/scripts/set_all_project_types_to_terra.rb
- rails/spec/lib/props_sanatizer_spec.rb
- rails/spec/models/kaiju/component_factory_spec.rb
- rails/spec/models/kaiju/component_json_spec.rb
- rails/spec/models/kaiju/component_spec.rb
- rails/spec/models/kaiju/project_json_spec.rb
- rails/spec/models/kaiju/project_spec.rb
- rails/spec/models/kaiju/property_json_spec.rb
- rails/spec/models/kaiju/property_spec.rb
- rails/spec/models/kaiju/user_json_spec.rb
- rails/spec/models/kaiju/workspace_json_spec.rb
- rails/spec/models/kaiju/workspace_spec.rb
Adding project type to both workspace and component.
@cerner/kaiju
> Apply project type to workspace and component

- changelog.md
- rails/client/app/bundles/kaiju/components/LaunchPage/components/LaunchScreen/LaunchScreen.scss
- rails/client/app/bundles/kaiju/components/Project/components/StoryBoard/StoryBoard.scss
Taking down the holiday decorations.
@cerner/kaiju
> Updated - Switched to default Kaiju theme

- changelog.md
- rails/client/.babelrc
- rails/client/app/bundles/kaiju/components/LaunchPage/components/LaunchScreen/LaunchScreen.jsx
- rails/client/app/bundles/kaiju/components/LaunchPage/containers/GridContainer.jsx
Added a Deleted projects folder to the launch page that will allow recovering inactive projects.
Still waiting for some UX feedback. 
@cerner/kaiju
> Added - Ability to recover deleted projects from the launch page

- rails/app/models/kaiju/model_json.rb
- rails/app/models/kaiju/project_json.rb
Inactive workspaces are being added to the count incorrectly.
@cerner/kaiju
> Ignore inactive workspaces in count

- changelog.md
- rails/app/controllers/workspaces_controller.rb
- rails/app/helpers/workspaces_helper.rb
- rails/client/.stylelintrc
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Duplicate/Duplicate.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Duplicate/Duplicate.scss
- rails/client/app/bundles/kaiju/components/Project/containers/DuplicateWorkspaceContainer.jsx
- rails/client/app/bundles/kaiju/components/common/Spinner/Spinner.jsx
- rails/client/app/bundles/kaiju/components/common/Spinner/Spinner.scss
- rails/client/package-lock.json
Added a duplication option to each workspaces action bar.
- Duplicating your own workspace into the same project
- Duplicating your own workspace into a different project
- Duplicating your own workspace into a new project
- Duplicating someone else's workspace into an existing project
- Duplicating someone else's workspace into a new project
@cerner/kaiju
Resolves #6
> Added - Workspace duplication

- changelog.md
- node/package-lock.json
- node/package.json
- rails/client/package-lock.json
- rails/client/package.json
Importing the new Checkbox
Blocked until the code merge and release of [terra-kaiju-plugin](https://github.com/cerner/terra-kaiju-plugin/pull/3)
@cerner/kaiju
> Updated - Change log to announce the new Checkbox

- changelog.md
- rails/client/app/bundles/kaiju/components/Project/components/Browser/Browser.scss
- rails/client/app/bundles/kaiju/components/Project/components/Sandbox/Sandbox.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Sandbox/Sandbox.scss
- rails/client/app/bundles/kaiju/components/common/Alert/Alert.jsx
- rails/client/app/bundles/kaiju/components/common/Alert/Alert.scss
Resolves https://github.com/cerner/kaiju/issues/64
@cerner/kaiju
> Added - A read-only banner for unauthorized workspaces

- changelog.md
- node/package-lock.json
- node/package.json
- rails/client/app/bundles/kaiju/components/Project/components/Changelog/Changelog.jsx
- rails/client/package-lock.json
- rails/client/package.json
- rails/client/webpack.config.js
Updating the Changlog to announce:
- Added the Radio
- Added Tabs
- Added Status View
- Adding a footer to the Content Container
- Depreciating the Control
- Deprecating No data view
- Deprecating Error View
Depreciated the Control component
**Blocked** until the code merge and release of[ terra-kaiju-plugin](https://github.com/cerner/terra-kaiju-plugin/pull/8)
@cerner/kaiju
> Updated - Changelog to announce new components

- node/package-lock.json
- rails/client/app/bundles/kaiju/components/Component/Component.jsx
- rails/client/app/bundles/kaiju/components/Component/utilities/dispatcher.js
- rails/client/app/bundles/kaiju/components/LaunchPage/components/LaunchScreen/LaunchScreen.jsx
- rails/client/app/bundles/kaiju/components/LaunchPage/containers/GridContainer.jsx
- rails/client/app/bundles/kaiju/components/Project/Project.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Delete/Delete.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Duplicate/Duplicate.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Rename/Rename.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Share/Share.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Changelog/Changelog.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Form/Cloneable/Cloneable.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Form/ComponentSelect/ComponentSelect.jsx
- rails/client/app/bundles/kaiju/components/Project/components/StoryBoard/StoryBoard.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/ProjectNameContainer.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/TabContainer.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/menu/DeleteMenuItem.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/menu/NewMenuItem.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/menu/OpenMenuItem.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/menu/RenameMenuItem.jsx
- rails/client/app/bundles/kaiju/components/Project/containers/menu/ShareMenuItem.jsx
- rails/client/app/bundles/kaiju/utilities/axios.js
- rails/client/package-lock.json
- rails/client/package.json
- Replaced super agent with axios.
- Created an axios wrapper to preset request / response headers.
Resolves: https://github.com/cerner/kaiju/issues/72
@cerner/kaiju
> Updated - Replaced superagent with axios

- rails/client/package-lock.json
- rails/client/package.json
- rails/client/tests/component/actions.test.js
- rails/client/tests/component/components.test.js
- rails/client/tests/component/refreshedComponent.test.js
- rails/client/tests/component/selectedComponent.test.js
- rails/client/tests/launchPage/actions.test.js
- rails/client/tests/launchPage/searchFilter.test.js
- rails/client/tests/launchPage/selectedListItem.test.js
- rails/client/tests/project/actions.test.js
- rails/client/tests/project/activeWorkspace.test.js
- rails/client/tests/project/canvasSize.test.js
- rails/client/tests/project/components.test.js
- rails/client/tests/project/project.test.js
- rails/client/tests/project/referenceComponents.test.js
- rails/client/tests/project/root.test.js
- rails/client/tests/project/selectedComponent.test.js
- rails/client/tests/project/tabs.test.js
- rails/client/tests/project/user.test.js
- rails/client/tests/project/workspaces.test.js
- rails/package.json
Adds Jest testing for client redux actions and reducers.
Resolves #88.
@cerner/kaiju
> Setup Jest testing suite for redux actions and reducers

- rails/changelog.md
- rails/client/app/bundles/kaiju/components/Project/components/Changelog/Changelog.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ComponentSearch/ComponentSearch.scss
- rails/client/app/bundles/kaiju/components/Project/components/SectionHeader/SectionHeader.scss
- rails/client/app/bundles/kaiju/components/Project/components/Sidebar/Sidebar.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Sidebar/Sidebar.scss
Added the ability to resize the sidebar and layers.
Resolves #7.
@cerner/kaiju
> Added - Sidebar and layer resizing

- rails/client/app/bundles/kaiju/components/LaunchPage/components/LaunchScreen/LaunchScreen.jsx
- rails/client/app/bundles/kaiju/components/LaunchPage/containers/ListContainer.jsx
- rails/client/app/bundles/kaiju/components/LaunchPage/reducers/selectedListItem.js
- rails/client/package-lock.json
- rails/client/tests/launchPage/selectedListItem.test.js
After gathering some feedback many users would like "My Projects" open by default on the Launch Page. 
Resolves #100.
@cerner/kaiju
> Updated - Open My Projects by default on the Launch Page

- node/package-lock.json
- node/package.json
- rails/client/app/bundles/kaiju/components/Guide/Guide.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/ActionBar.jsx
- rails/client/app/bundles/kaiju/components/Project/components/ActionBar/Share/Share.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Form/ComponentSelect/ComponentSelect.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Form/ComponentSelect/ComponentSelect.scss
- rails/client/package-lock.json
- rails/client/package.json
This change enables horizontal scrolling within the component search so a user can view the entire text display.
This change also humanizes the filter search. Previously the filter would compare against the camelCase value. Humanizing the value enables a more natural search. Comparing "Item View -> Item View" instead of "Item View -> ItemView" 
Resolves #107 
@cerner/kaiju
> Updated - Enabled horizontal scrolling for component search

- node/package-lock.json
- node/package.json
- rails/changelog.md
- rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.jsx
- rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.scss
- rails/client/package-lock.json
- rails/client/package.json
- rails/lib/component_information.rb
Added a link for accessing each components official documentation resources available on [terra-ui](http://engineering.cerner.com/terra-ui/#/site/components) site.
Resolves #119 
@cerner/kaiju
> Added - Component documentation links

- node/package-lock.json
- node/package.json
- rails/changelog.md
- rails/client/package-lock.json
- rails/client/package.json
> Updating change log to announce new Terra components

- node/package-lock.json
- node/package.json
- package-lock.json
- package.json
- rails/changelog.md
- rails/client/package-lock.json
- rails/client/package.json
- Bumped terra-kaiju-plugin to latest release
- Bumped foreman dev dependency
- Updated change log
@cerner/kaiju
> Updated - Bumped terra-kaiju-plugin

- rails/changelog.md
- rails/client/app/bundles/kaiju/components/Project/Project.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Form/Child/Child.scss
- rails/client/app/bundles/kaiju/components/Project/components/Layer/Layer.jsx
- rails/client/app/bundles/kaiju/components/Project/components/Layer/Layer.scss
- rails/client/app/bundles/kaiju/components/Project/components/Layers/Layers.jsx
- rails/client/app/bundles/kaiju/components/Project/utilities/drag.js
- rails/client/app/bundles/kaiju/components/Project/utilities/messenger.js
- rails/client/package-lock.json
- Added the ability to drag and drop into the placeholders within the layers.
@cerner/kaiju
> Added - The ability to drop into layer placeholders

- rails/client/jest.config.js
- rails/client/package-lock.json
Adding testURL to jest config to resolve issue related to jsdom / jest issues with the jsdom 11.12.0 release.
https://github.com/jsdom/jsdom/issues/2304
https://github.com/facebook/jest/issues/6766
@cerner/kaiju
> Bumping dependencies 

- rails/app/controllers/health_controller.rb
Checking the status of Redis in the health check
@cerner/kaiju
> Update - Include Redis in the health check

- rails/changelog.md
- rails/client/app/bundles/kaiju/components/Project/components/DraggableItem/DraggableItem.scss
- rails/client/package-lock.json
- rails/client/package.json
- rails/client/plugins/gather-dependencies.js
- Updated the changelog to announce new components
- Bumped the package lock to pull in the latest releases
@cerner/kaiju
> Update - Bump to latest components

- README.md
I updated the copyright date from 2017 to 2018.
> UPDATE copyright date from 2017 to 2018.

- rails/client/package-lock.json
> Update - Bump to latest dependencies

- rails/app/controllers/health_controller.rb
- rails/client/package-lock.json
Added heath check logging to the standard output. 
@cerner/kaiju
> Added health check logging

- rails/client/package-lock.json
Updated the component dependencies.
@cerner/kaiju
> Update - Bump package lock dependencies

- node/package-lock.json
- node/package.json
Lets update webpack dev server!
If you have anything else that you think may be relevant to this issue, list it here. Additional information can help us better understand your changes and speed up the review process.
@cerner/kaiju
> update webpack dev server

- rails/client/package-lock.json
Bumping dependencies.
@cerner/kaiju
> Updated - Bump component versions

- Dockerfile
- docker-compose.yml
- rails/client/package-lock.json
- rails/config/application.rb
- rails/config/environments/development.rb
- rails/config/environments/production.rb
- rails/config/environments/test.rb
- rails/config/initializers/redis.rb
- rails/config/initializers/session_store.rb
- rails/config/redis.yml
- rails/docker-compose.yml
Enabled an optional redis sentinel configuration. 
- Increased the connection pool size to 50.
@cerner/kaiju
> Update - Enable Redis Sentinel Configuration

- rails/config/puma.rb
Re-arrange kaiju puma config to start service in clustered mode instead of single process
Double your pleasure, double your fun.
@cerner/kaiju
> Run puma in clustered mode.

- rails/config/redis.yml
> Remove redis_sentinel_url if sentinels are not present

- rails/client/package-lock.json
- rails/client/package.json
> Update Terra Components

- rails/client/package-lock.json
Updated the lock file dependencies.
@cerner/kaiju
> Update package-lock dependencies

- rails/client/package-lock.json
> Update package lock

- rails/client/package-lock.json
- rails/client/package.json
> Bump package dependencies

- rails/client/package-lock.json
- rails/client/package.json
> Bumping dependencies

- rails/client/package-lock.json
- rails/client/package.json
Update to the latest version of the terra plugin.
@cerner/kaiju
> Update to the latest terra plugin version

- rails/client/package-lock.json
Bumped the package dependencies
@cerner/kaiju
> Bump dependencies

- rails/client/package-lock.json
- rails/client/package.json
> Update package dependencies

- client/app/bundles/kaiju/components/Component/Component.jsx
- client/package-lock.json
- client/package.json
This PR updates the Kaiju Sandbox to be wrapped with terra-base 5.0.
> Update to terra-base 5.0

- Gemfile
- Gemfile.lock
- client/package-lock.json
- client/package.json
- config/webpacker.yml
This PR fixes an issue with css assets not being correctly loaded into the dom when bundled in development.
> Fix webpacker extracting css in development

- client/app/bundles/kaiju/components/Preview/Preview.jsx
- client/package-lock.json
This PR fixes an issue with the preview height collapsing. A recent update upgraded terra-base to the latest major version. This version of terra-base does not wrap content in a div and does not honor classNames.
@cerner/kaiju
> Fix css not being applied to the preview
